### ISSUE TITLE
似乎支付宝的红包不能抢

### ISSUE THREAD

**Issue by cyqjyzp** [waylife/RedEnvelopeAssistant#6]
想做一个抢支付宝红包的app，但跳转到支付宝的聊天页面后，发现用代码找不到里面的红包view，也就点不开红包。下载了您的代码发现支付宝的红包也没有反应，代码里面似乎只支持微信的。

**Comment by waylife** [comment]
15年的时候清空支付宝相关的数据再次登录就可以再次登录抢红包，现在应该不行了。
